### ISSUE TITLE
[ Feature ] Suggest configuration files / An idea of evolution

### ISSUE THREAD

**Issue by micisse** [entrepeneur4lyf/pmdaemon#1]
Hello ! _Nice find!_ I'm not a PM2 user but rather a “**supervisor**” user. And I was wondering if it wouldn't be interesting to add the **notion of configuration files** as with “**supervisor**” for processes. _At the moment, you have to do everything on the command line_

![Image](https://github.com/user-attachments/assets/7319401d-9da2-49eb-9b4e-5f2345834c1e)

**A configuration file may be more practical and easier to read**. For example:

_Maybe here /etc/pmdaemon/*_
_Maybe here /etc/pmdaemon/conf.d/*_
_Maybe here  ~/.config/pmdaemon/conf.d/*_

```toml
# Supervisor https://supervisord.org/
[program:myapp]
process_name=%(program_name)s
command=command to be executed
autostart=true
autorestart=true
user=mcisse
redirect_stderr=true
stdout_logfile=/var/log/app.log
# and so on [...]
# OR

name=my-app
# Description
instances=4
port=3000-3003
# Description
maxmemory=512M
env="NODE_ENV=production OTHER_VAR_ENV=other"
cwd=command to be executed
logfile=/var/log/app.log
healthcheckurl=http://localhost:9615/health
wait=ready
# and so on [...]
```

**_An idea of evolution_**
